CREATE TABLE IF NOT EXISTS produto (
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    valor_fornecedor DOUBLE NOT NULL,
    quantidade_estoque INT NOT NULL
);

CREATE TABLE IF NOT EXISTS movimento_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    tipo_movimentacao VARCHAR(255) NOT NULL,
    valor_venda DOUBLE,
    data_movimentacao TIMESTAMP NOT NULL,
    quantidade_movimentada INT NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES produto(codigo)
);